sudo: required
language: node_js
dist: trusty
node_js: stable

branches:
  only:
    - structure

install:
  - sudo apt-get install software-properties-common -qq
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install ansible -qq

script:
  - ansible-playbook .test.yml
